### PR TITLE
Adding routing package: Bogdanp/elm-route.

### PR DESCRIPTION
**Pull request by mccrodp**
Hey, thanks for the repo, it was a happy find, Bootstrap package, etc., all working with Elm 0.18.

I'm new enough to Elm and looking to make a good scaffold / starting point for more complete Elm applications. I've made a small step towards that by adding integration from your repo with the `Bogdanp/elm-route` repo. Not sure if that's something you're interested in, or if you want this to be a minimal approach, but I've included a WIP PR for starters.

Do you use Docker? I've contemplated Dockerising either this repo, or with the addons I require. Routing and separating other components, somewhat similar to this for 0.17: https://github.com/Gizra/generator-elmlang-example

### CODE REVIEW

**Comment by mathieul** [comment]
Thank you for this PR, I'm glad this code was useful to you.

A richer code example is a good idea, if the user doesn't need it they can always delete it and it doesn't add much complexity. The example should work out of the box to be useful to newcomers though: do you have a basic server that would serve a static JSON response to `/api/posts`?

A nitpick: I'm wondering if splitting the source code in 3 files is premature for an example. Richard Feldman, Mike Clark at Pragmatic Studio, Murphy Randle at Elm Town, etc... recommend sticking to a single file until the app itself starts requiring being split up. Anyway I don't have a strong opinion for providing a code example, just thought I'd mention it.

I don't use Docker for my side projects. Adding docker to this repo might start being too specific so using a generator sounds like a more flexible option.

**Comment by mccrodp** [comment]
Hey, thanks for reply.

>The example should work out of the box to be useful to newcomers though: do you have a basic server that would serve a static JSON response to /api/posts?

This is just directly integrated from the routing package example. It could be used in a Dockerised version of the repo, bringing up a server to provide the api endpoint. However, in this case after deciding not to add this, it should be removed and keep the `Route.elm` only.

>I'm wondering if splitting the source code in 3 files is premature for an example...recommend sticking to a single file until the app itself starts requiring being split up. Anyway I don't have a strong opinion for providing a code example, just thought I'd mention it.

It's interesting, as I found this to be a blocker in all code examples. I can't think of a practical use case for a large app or even a small SPA where you wouldn't split out the files into separate "components". It would be 2 files now that `Data.elm` is removed. Do you have any suggestion for providing say a separate folder per example? i.e. - your original example in 1 file, this example w/ routing in a folder with 2 .elm files and any subsequent examples in future.

Yes, let's leave Docker out for the moment, I might create a separate repo with this elsewhere, as it might be a blocker for people.

**Comment by mathieul** [comment]
With Brunch you can just drop files into the `public/` folder and they will be served by brunch when serving with `brunch watch --server`. So just adding a file `public/api/posts` containing a list of posts as JSON will just work.

Regarding file structure I didn't mean an Elm app shouldn't be split into several files. What I meant is to start with one file and start extracting when the file becomes difficult to work with. The modules you will have extracted in the end will likely be very different than those you would have expected when starting. You will probably not have all your decoder and tasks into a `Data` file or folder. Most likely you'd have a `Post` module with its type, decoders, maybe tasks. So instead of making a choice when you don't know, you let the application development process tell you how to structure it.

But that's probably not really that important here, it's just something I realized recently and I'm having trouble not getting down the rabbit hole 😉.

That sounds great to me. I would just add a static `public/api/posts` JSON file so the example works out of the box, and style the navigation links using bootstrap classes.

Thanks

**Comment by mccrodp** [comment]
>With Brunch you can just drop files into the public/ folder and they will be served by brunch when serving with brunch watch --server. So just adding a file public/api/posts containing a list of posts as JSON will just work.

That's great!

>What I meant is to start with one file and start extracting when the file becomes difficult to work with.

Yep, makes sense. Knew what you meant, I was more referring to not seeing any examples with how files should be split up, so I didn't know how initially. The idea of letting the actual app decide is a good one though.

>I would just add a static public/api/posts JSON file so the example works out of the box, and style the navigation links using bootstrap classes.

Will do 😄

**Comment by mccrodp** [comment]
ping @mathieul

**Comment by mathieul** [comment]
Looks great, thanks @mccrodp!

**Pull request merged**
